### ISSUE TITLE
Add a team construct

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#66]
Team --> The bunch of people doing an assessment together - responsible for the assessment.

Maybe this is a group of labels?

**Comment by mvillis** [comment]
looks like prod is broken. having a look

**Comment by mvillis** [comment]
not sure but adding three teams into prod then running a migrate seems to have fixed it:

```
$ heroku run python manage.py migrate --app measuremate
Running python manage.py migrate on measuremate... up, run.6127
Operations to perform:
  Apply all migrations: measure_mate, auth, sessions, admin, contenttypes
Running migrations:
  Rendering model states... DONE
  Applying measure_mate.0012_auto_20160223_0649... OK
  Applying measure_mate.0013_auto_20160224_0006... OK
  Applying measure_mate.0014_auto_20160224_0207... OK
  Applying measure_mate.0015_merge... OK
```

**Comment by rloomans** [comment]
Odd. Teams should be optional, and the migrate should happen on every deploy.

## 

Robert Loomans

On 26 Feb 2016, at 21:31, Mike Villis <notifications@github.com<mailto:notifications@github.com>> wrote:

not sure but adding three teams into prod then running a migrate seems to have fixed it:

$ heroku run python manage.py migrate --app measuremate
Running python manage.py migrate on measuremate... up, run.6127
Operations to perform:
  Apply all migrations: measure_mate, auth, sessions, admin, contenttypes
Running migrations:
  Rendering model states... DONE
  Applying measure_mate.0012_auto_20160223_0649... OK
  Applying measure_mate.0013_auto_20160224_0006... OK
  Applying measure_mate.0014_auto_20160224_0207... OK
  Applying measure_mate.0015_merge... OK

—
Reply to this email directly or view it on GitHubhttps://github.com/mvillis/measure-mate/issues/66#issuecomment-189232294.

---

This e-mail is sent by Suncorp Group Limited ABN 66 145 290 124 or one of its related entities "Suncorp".
Suncorp may be contacted at Level 28, 266 George Street, Brisbane or on 13 11 55 or at suncorp.com.au.
The content of this e-mail is the view of the sender or stated author and does not necessarily reflect the view of Suncorp. The content, including attachments, is a confidential communication between Suncorp and the intended recipient. If you are not the intended recipient, any use, interference with, disclosure or copying of this e-mail, including attachments, is unauthorised and expressly prohibited. If you have received this e-mail in error please contact the sender immediately and delete the e-mail and any attachments from your system.

**Comment by mvillis** [comment]
I'm still not sure what's happened. does appear to be enforcing a team for assessments:

<img width="604" alt="screen shot 2016-02-27 at 5 05 06 pm" src="https://cloud.githubusercontent.com/assets/3509371/13371532/51ba33c8-dd74-11e5-9ead-a8f466e1a97c.png">

Here was the error in the deploy (failed silently)

```
django.db.utils.ProgrammingError: Problem installing fixture '/app/measure_mate/fixtures/assessment.json': Could not load measure_mate.Assessment(pk=1): column "team_id" of relation "measure_mate_assessment" does not exist
```

Full Output:

```
-----> Fetching set buildpack https://github.com/ddollar/heroku-buildpack-multi.git... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 5.6.0...
       Using default npm version: 3.6.0
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)

       > measure-mate@0.0.1 postinstall /tmp/build_a836c5b3e488e64c72314474266263d7/mvillis-measure-mate-13fbf1c
       > ./node_modules/bower/bin/bower install

       bower react-select#v1.0.0-beta9       not-cached https://github.com/JedWatson/react-select.git#v1.0.0-beta9
       bower react-select#v1.0.0-beta9          resolve https://github.com/JedWatson/react-select.git#v1.0.0-beta9
       bower babel#*                         not-cached git://github.com/Micua/babel.git#*
       bower babel#*                            resolve git://github.com/Micua/babel.git#*
       bower bootstrap#~3.3.6                not-cached git://github.com/twbs/bootstrap.git#~3.3.6
       bower bootstrap#~3.3.6                   resolve git://github.com/twbs/bootstrap.git#~3.3.6
       bower react#~0.14.7                   not-cached git://github.com/facebook/react-bower.git#~0.14.7
       bower react#~0.14.7                      resolve git://github.com/facebook/react-bower.git#~0.14.7
       bower jquery#~2.1.4                   not-cached git://github.com/jquery/jquery-dist.git#~2.1.4
       bower jquery#~2.1.4                      resolve git://github.com/jquery/jquery-dist.git#~2.1.4
       bower react-loader#~2.0.0             not-cached git://github.com/quickleft/react-loader.git#~2.0.0
       bower react-loader#~2.0.0                resolve git://github.com/quickleft/react-loader.git#~2.0.0
       bower plotly.js#^1.5.2                not-cached git://github.com/plotly/plotly.js.git#^1.5.2
       bower plotly.js#^1.5.2                   resolve git://github.com/plotly/plotly.js.git#^1.5.2
       bower react-bootstrap#~0.28.3         not-cached git://github.com/react-bootstrap/react-bootstrap-bower.git#~0.28.3
       bower react-bootstrap#~0.28.3            resolve git://github.com/react-bootstrap/react-bootstrap-bower.git#~0.28.3
       bower moment#~2.11.2                  not-cached git://github.com/moment/moment.git#~2.11.2
       bower moment#~2.11.2                     resolve git://github.com/moment/moment.git#~2.11.2
       bower underscore#~1.8.3               not-cached git://github.com/jashkenas/underscore.git#~1.8.3
       bower underscore#~1.8.3                  resolve git://github.com/jashkenas/underscore.git#~1.8.3
       bower babel#*                           checkout master
       bower jquery#~2.1.4                     download https://github.com/jquery/jquery-dist/archive/2.1.4.tar.gz
       bower plotly.js#^1.5.2                  download https://github.com/plotly/plotly.js/archive/v1.5.2.tar.gz
       bower react-select#v1.0.0-beta9         checkout v1.0.0-beta9
       bower react-loader#~2.0.0               download https://github.com/quickleft/react-loader/archive/v2.0.0.tar.gz
       bower react#~0.14.7                     download https://github.com/facebook/react-bower/archive/v0.14.7.tar.gz
       bower react-bootstrap#~0.28.3           download https://github.com/react-bootstrap/react-bootstrap-bower/archive/v0.28.3.tar.gz
       bower bootstrap#~3.3.6                  download https://github.com/twbs/bootstrap/archive/v3.3.6.tar.gz
       bower underscore#~1.8.3                 download https://github.com/jashkenas/underscore/archive/1.8.3.tar.gz
       bower moment#~2.11.2                    download https://github.com/moment/moment/archive/2.11.2.tar.gz
       bower react-loader#~2.0.0                extract archive.tar.gz
       bower babel#*                       invalid-meta babel is missing "main" entry in bower.json
       bower babel#*                       invalid-meta babel is missing "ignore" entry in bower.json
       bower babel#*                           resolved git://github.com/Micua/babel.git#d54d59ff74
       bower react-bootstrap#~0.28.3            extract archive.tar.gz
       bower underscore#~1.8.3                  extract archive.tar.gz
       bower react#~0.14.7                      extract archive.tar.gz
       bower jquery#~2.1.4                      extract archive.tar.gz
       bower moment#~2.11.2                     extract archive.tar.gz
       bower react-loader#~2.0.0           invalid-meta react-loader is missing "ignore" entry in bower.json
       bower react-loader#~2.0.0               resolved git://github.com/quickleft/react-loader.git#2.0.0
       bower spin.js#2.x                     not-cached git://github.com/fgnass/spin.js.git#2.x
       bower spin.js#2.x                        resolve git://github.com/fgnass/spin.js.git#2.x
       bower spin.js#2.x                       download https://github.com/fgnass/spin.js/archive/2.3.2.tar.gz
       bower react-bootstrap#~0.28.3           resolved git://github.com/react-bootstrap/react-bootstrap-bower.git#0.28.3
       bower react#>=0.14.0                  not-cached git://github.com/facebook/react-bower.git#>=0.14.0
       bower react#>=0.14.0                     resolve git://github.com/facebook/react-bower.git#>=0.14.0
       bower react#>=0.14.0                    download https://github.com/facebook/react-bower/archive/v0.14.7.tar.gz
       bower spin.js#2.x                        extract archive.tar.gz
       bower react#~0.14.7                     resolved git://github.com/facebook/react-bower.git#0.14.7
       bower react-select#v1.0.0-beta9         mismatch Version declared in the json (1.0.0-beta7) is different than the resolved one (1.0.0-beta9)
       bower bootstrap#~3.3.6                   extract archive.tar.gz
       bower react#>=0.14.0                     extract archive.tar.gz
       bower underscore#~1.8.3                 resolved git://github.com/jashkenas/underscore.git#1.8.3
       bower react#>=0.14.0                    resolved git://github.com/facebook/react-bower.git#0.14.7
       bower spin.js#2.x                       resolved git://github.com/fgnass/spin.js.git#2.3.2
       bower react-select#v1.0.0-beta9         resolved https://github.com/JedWatson/react-select.git#1.0.0-beta9
       bower classnames#^2.2.0               not-cached git://github.com/JedWatson/classnames.git#^2.2.0
       bower classnames#^2.2.0                  resolve git://github.com/JedWatson/classnames.git#^2.2.0
       bower react-input-autosize#^0.6.5     not-cached git://github.com/JedWatson/react-input-autosize.git#^0.6.5
       bower react-input-autosize#^0.6.5        resolve git://github.com/JedWatson/react-input-autosize.git#^0.6.5
       bower classnames#^2.2.0                 download https://github.com/JedWatson/classnames/archive/v2.2.3.tar.gz
       bower react-input-autosize#^0.6.5       download https://github.com/JedWatson/react-input-autosize/archive/v0.6.8.tar.gz
       bower classnames#^2.2.0                  extract archive.tar.gz
       bower react-input-autosize#^0.6.5        extract archive.tar.gz
       bower classnames#^2.2.0                 resolved git://github.com/JedWatson/classnames.git#2.2.3
       bower react-input-autosize#^0.6.5       resolved git://github.com/JedWatson/react-input-autosize.git#0.6.8
       bower plotly.js#^1.5.2                   extract archive.tar.gz
       bower jquery#~2.1.4                     resolved git://github.com/jquery/jquery-dist.git#2.1.4
       bower bootstrap#~3.3.6                  resolved git://github.com/twbs/bootstrap.git#3.3.6
       bower moment#~2.11.2                    resolved git://github.com/moment/moment.git#2.11.2
       bower plotly.js#^1.5.2                  resolved git://github.com/plotly/plotly.js.git#1.5.2
       bower babel#*                            install babel#d54d59ff74
       bower react-loader#~2.0.0                install react-loader#2.0.0
       bower react-bootstrap#~0.28.3            install react-bootstrap#0.28.3
       bower react#~0.14.7                      install react#0.14.7
       bower underscore#~1.8.3                  install underscore#1.8.3
       bower spin.js#2.x                        install spin.js#2.3.2
       bower react-select#v1.0.0-beta9          install react-select#1.0.0-beta9
       bower classnames#^2.2.0                  install classnames#2.2.3
       bower react-input-autosize#^0.6.5        install react-input-autosize#0.6.8
       bower jquery#~2.1.4                      install jquery#2.1.4
       bower bootstrap#~3.3.6                   install bootstrap#3.3.6
       bower moment#~2.11.2                     install moment#2.11.2
       bower plotly.js#^1.5.2                   install plotly.js#1.5.2

       babel#d54d59ff74 measure_mate/static/components/babel

       react-loader#2.0.0 measure_mate/static/components/react-loader
       └── spin.js#2.3.2

       react-bootstrap#0.28.3 measure_mate/static/components/react-bootstrap
       └── react#0.14.7

       react#0.14.7 measure_mate/static/components/react

       underscore#1.8.3 measure_mate/static/components/underscore

       spin.js#2.3.2 measure_mate/static/components/spin.js

       react-select#1.0.0-beta9 measure_mate/static/components/react-select
       ├── classnames#2.2.3
       └── react-input-autosize#0.6.8

       classnames#2.2.3 measure_mate/static/components/classnames

       react-input-autosize#0.6.8 measure_mate/static/components/react-input-autosize

       jquery#2.1.4 measure_mate/static/components/jquery

       bootstrap#3.3.6 measure_mate/static/components/bootstrap
       └── jquery#2.1.4

       moment#2.11.2 measure_mate/static/components/moment

       plotly.js#1.5.2 measure_mate/static/components/plotly.js
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
       └── bower@1.7.7

=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python.git
=====> Detected Framework: Python
     $ pip install -r requirements.txt
     $ python manage.py collectstatic --noinput
       1422 static files copied to '/app/measure_mate/staticfiles'.
-----> Running post-compile hook
Operations to perform:
  Apply all migrations: admin, contenttypes, measure_mate, auth, sessions
Running migrations:
  Rendering model states... DONE
  Applying measure_mate.0011_team... OK
  Applying measure_mate.0012_auto_20160223_0649...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 482, in alter_field
    old_db_params, new_db_params, strict)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql/schema.py", line 110, in _alter_field
    new_db_params, strict,
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 717, in _alter_field
    self.execute(self._create_fk_sql(model, new_field, "_fk_%(to_table)s_%(to_column)s"))
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: insert or update on table "measure_mate_assessment" violates foreign key constraint "measure_mate_asses_template_id_a871e848_fk_measure_mate_team_id"
DETAIL:  Key (template_id)=(1) is not present in table "measure_mate_team".
Installed 121 object(s) from 4 fixture(s)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 158, in load_label
    obj.save(using=self.using)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/serializers/base.py", line 201, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 793, in _save_table
    forced_update)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 843, in _do_update
    return filtered._update(values) > 0
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 645, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1149, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture '/app/measure_mate/fixtures/assessment.json': Could not load measure_mate.Assessment(pk=1): column "team_id" of relation "measure_mate_assessment" does not exist
LINE 1: ...14.525000+00:00'::timestamptz, "template_id" = 1, "team_id" ...
                                                             ^
Using release configuration from last framework (Python).
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 78.2M
-----> Launching...
       Released v100
       https://measuremate.herokuapp.com/ deployed to Heroku
```

**Comment by mvillis** [comment]
apologies.... the reason in fixtures failed was because the migrate failed

```
django.db.utils.IntegrityError: insert or update on table "measure_mate_assessment" violates foreign key constraint "measure_mate_asses_template_id_a871e848_fk_measure_mate_team_id"
DETAIL:  Key (template_id)=(1) is not present in table "measure_mate_team".
Installed 121 object(s) from 4 fixture(s)
Traceback (most recent call last):
```

looks like form validation fails for assessments because the model does not include `blank=True`. 
https://docs.djangoproject.com/en/1.9/ref/models/fields/#blank

I have a feeling that the issue may be because we have the same related_name in the assessment model? I don't understand why there would be a constraint linking template id with team id:

``` measure_mate_asses_template_id_a871e848_fk_measure_mate_team_id```
```

**Comment by rloomans** [comment]
I wonder if doing a flush, migrate and loaddata will resolve it.

## 

Robert Loomans

On 27 Feb 2016, at 17:34, Mike Villis <notifications@github.com<mailto:notifications@github.com>> wrote:

apologies.... the reason in fixtures failed was because the migrate failed

django.db.utils.IntegrityError: insert or update on table "measure_mate_assessment" violates foreign key constraint "measure_mate_asses_template_id_a871e848_fk_measure_mate_team_id"
DETAIL:  Key (template_id)=(1) is not present in table "measure_mate_team".
Installed 121 object(s) from 4 fixture(s)
Traceback (most recent call last):

looks like form validation fails for assessments because the model does not include blank=True.
https://docs.djangoproject.com/en/1.9/ref/models/fields/#blank

I have a feeling that the issue may be because we have the same related_name in the assessment model? I don't understand why there would be a constraint linking template id with team id:

—
Reply to this email directly or view it on GitHubhttps://github.com/mvillis/measure-mate/issues/66#issuecomment-189600390.

---

This e-mail is sent by Suncorp Group Limited ABN 66 145 290 124 or one of its related entities "Suncorp".
Suncorp may be contacted at Level 28, 266 George Street, Brisbane or on 13 11 55 or at suncorp.com.au.
The content of this e-mail is the view of the sender or stated author and does not necessarily reflect the view of Suncorp. The content, including attachments, is a confidential communication between Suncorp and the intended recipient. If you are not the intended recipient, any use, interference with, disclosure or copying of this e-mail, including attachments, is unauthorised and expressly prohibited. If you have received this e-mail in error please contact the sender immediately and delete the e-mail and any attachments from your system.

**Comment by mvillis** [comment]
it's all running again perfectly.
just don't understand why creating the 3 teams follow by running a migrate was the fix :-(

btw...I never had an issue locally running the migrate........but i'm not using all the setup data......

i'm guessing when we're serious about prod prod we won't be running the assessment fixture.

**Comment by mvillis** [comment]
@rloomans are you happy to refactor this one? I can help out just yell!

**Comment by rloomans** [comment]
@mvillis almost done... just have to clean up the lint complaints

**Comment by mvillis** [comment]
nice work. Looking great!

**Comment by mvillis** [comment]
anything left on this one?

**Comment by rloomans** [comment]
The validation error message is broken. 

I'll leave editing team details for another card. 

## 

Robert Loomans

**Comment by mvillis** [comment]
#131 created

**Comment by rloomans** [comment]
Validation is fixed.
